src/Greetik/YtvideoBundle/Entity/Ytvideo.php
<?php

namespace Greetik\YtvideoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Ytvideo
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Greetik\YtvideoBundle\Entity\YtvideoRepository")
 * @ORM\Table(name="ytvideo")
 */
class Ytvideo {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @Assert\Length(max=255)
     * @var string
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="comments", type="text", nullable=true)
     */
    private $comments;

    /**
     * @var integer
     *
     * @ORM\Column(name="numorder", type="integer", nullable=true)
     */
    private $numorder;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=255)
     * @Assert\Url( message = "{{ value }} no es una url válida")
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @var string
     *
     * @ORM\Column(name="idyt", type="string", length=255)
     */
    private $idyt;

    /**
     * @var integer
     *
     * @ORM\Column(name="item_id", type="integer", nullable=true)
     */
    private $itemid;

    /**
     * @Assert\Length(max=255)
     * @var string
     *
     * @ORM\Column(name="item_type", type="string", length=255)
     */
    private $itemtype;

    /**
     * @Assert\Length(max=255)
     * @var string
     *
     * @ORM\Column(name="platform", type="string", length=255, nullable=true)
     */
    private $platform;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Ytvideo
     */
    public function setTitle($title) {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Set comments
     *
     * @param string $comments
     * @return Ytvideo
     */
    public function setComments($comments) {
        $this->comments = $comments;

        return $this;
    }

    /**
     * Get comments
     *
     * @return string 
     */
    public function getComments() {
        return $this->comments;
    }

    /**
     * Set numorder
     *
     * @param integer $numorder
     * @return Ytvideo
     */
    public function setNumorder($numorder) {
        $this->numorder = $numorder;

        return $this;
    }

    /**
     * Get numorder
     *
     * @return integer 
     */
    public function getNumorder() {
        return $this->numorder;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Ytvideo
     */
    public function setPath($path) {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath() {
        return $this->path;
    }

    /**
     * Set idyt
     *
     * @param string $idyt
     * @return Ytvideo
     */
    public function setIdyt($idyt) {
        $this->idyt = $idyt;

        return $this;
    }

    /**
     * Get idyt
     *
     * @return string 
     */
    public function getIdyt() {
        return $this->idyt;
    }

    /**
     * Set itemid
     *
     * @param integer $itemid
     *
     * @return Ytvideo
     */
    public function setItemid($itemid) {
        $this->itemid = $itemid;

        return $this;
    }

    /**
     * Get itemid
     *
     * @return integer
     */
    public function getItemid() {
        return $this->itemid;
    }

    /**
     * Set itemtype
     *
     * @param string $itemtype
     *
     * @return Ytvideo
     */
    public function setItemtype($itemtype) {
        $this->itemtype = $itemtype;

        return $this;
    }

    /**
     * Get itemtype
     *
     * @return string
     */
    public function getItemtype() {
        return $this->itemtype;
    }

    /**
     * Set platform
     *
     * @param string $platform
     *
     * @return Ytvideo
     */
    public function setPlatform($platform) {
        $this->platform = $platform;

        return $this;
    }

    /**
     * Get platform
     *
     * @return string
     */
    public function getPlatform() {
        return $this->platform;
    }

    public function getThumbnail() {
        switch ($this->platform) {
            case 'vimeo':
                $hash = unserialize(file_get_contents("http://vimeo.com/api/v2/video/$this->idyt.php"));
                return $hash[0]['thumbnail_large'];
        }

        return 'http://img.youtube.com/vi/' . $this->idyt . '/0.jpg';
    }
    
    public function getEmbedurl(){
        switch ($this->platform) {
            case 'vimeo':
                return 'https://player.vimeo.com/video/'. $this->idyt . '?autoplay=1';
        }

        return 'https://www.youtube.com/embed/' . $this->idyt . '?autoplay=1';
    }

}

src/Greetik/YtvideoBundle/Form/Type/YtvideoType.php
<?php
    namespace Greetik\YtvideoBundle\Form\Type;
    
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\Form\Extension\Core\Type\UrlType;
    use Symfony\Component\Form\Extension\Core\Type\HiddenType;
    use Symfony\Component\Form\Extension\Core\Type\TextareaType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of YtvideoType
 *
 * @author Paco
 */
class YtvideoType extends AbstractType{
    public function buildForm(FormBuilderInterface $builder, array $options){
        $builder->add('title')
                    ->add('comments', TextareaType::class, array('required'=>false))
                    ->add('path', UrlType::class)
                    ->add('id_item', HiddenType::class, array("mapped" => false))
                    ->add('type', HiddenType::class, array("mapped" => false))
                    ->add('id', HiddenType::class, array("mapped" => false));
    }
    
    public function getName(){
        return 'Ytvideo';
    }
    
    public function getDefaultOptions(array $options){
        return array( 'data_class' => 'Greetik\YtvideoBundle\Entity\Ytvideo');
    }
}

src/Greetik/YtvideoBundle/Resources/views/Ytvideo/index.html.twig
{% extends '::base.html.twig' %}

{% block favicon %}<link rel="icon" type="image/x-icon" href="{{ asset('bundles/beinterface/img/favicon.png') }}" />{% endblock %}

 {% block stylesheets %}
 <!-- BEGIN THEME STYLES --> 
   <!-- BEGIN GLOBAL MANDATORY STYLES -->          
   <link href="{{ asset('bundles/beinterface/plugins/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css"/>
   <link href="{{ asset('bundles/beinterface/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
   <link href="{{ asset('bundles/beinterface/plugins/uniform/css/uniform.default.css') }}" rel="stylesheet" type="text/css"/>
   <!-- END GLOBAL MANDATORY STYLES -->
   <!-- BEGIN THEME STYLES --> 
   <link href="{{ asset('bundles/beinterface/css/style-metronic.css') }}" rel="stylesheet" type="text/css"/>
   <link href="{{ asset('bundles/beinterface/css/style.css') }}" rel="stylesheet" type="text/css"/>
   <link href="{{ asset('bundles/beinterface/css/style-responsive.css') }}" rel="stylesheet" type="text/css"/>
   <link href="{{ asset('bundles/beinterface/css/plugins.css') }}" rel="stylesheet" type="text/css"/>
   <link href="{{ asset('bundles/beinterface/css/themes/light.css') }}" rel="stylesheet" type="text/css" id="style_color"/>
   <link href="{{ asset('bundles/beinterface/css/custom.css') }}" rel="stylesheet" type="text/css"/>
   <!-- END THEME STYLES -->
 {% endblock %}

 {% block javascriptshead %} 
   
   <script src="{{ asset('bundles/beinterface/plugins/jquery-1.10.2.min.js') }}" type="text/javascript"></script>   
   <!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
   <script src="{{ asset('bundles/beinterface/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js') }}" type="text/javascript"></script>
   <script src="{{ asset('bundles/beinterface/plugins/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
   <script src="{{ asset('bundles/beinterface/plugins/jquery-slimscroll/jquery.slimscroll.min.js') }}" type="text/javascript"></script>
   <script src="{{ asset('bundles/beinterface/plugins/jquery.cookie.min.js') }}" type="text/javascript"></script>
   <script src="{{ asset('bundles/beinterface/plugins/uniform/jquery.uniform.min.js') }}" type="text/javascript" ></script>
   <script src="{{ asset('bundles/beinterface/scripts/custom.js') }}" type="text/javascript" ></script>
   <!-- END CORE PLUGINS -->
   
   {% endblock %}

 {% block body %}

     {% include 'BEInterfaceBundle:_Default:header.html.twig' %}
       <div class="clearfix"></div>
       <div class="page-container">
            {% include 'BEInterfaceBundle:_Default:mainmenu.html.twig' %}
            <div class="page-content">
                {% block breadcrumb %}{% include 'BEInterfaceBundle:_Default:breadcrumb.html.twig' %}{%endblock%}
                {% block maincontent %}

                    <div class="col-md-12 col-sm-12">
                    <div class="portlet box green">
                    <div class="portlet-title">
                     <div class="caption">¡Bienvenido Administrador!</div>
                    </div>
                    <div class="portlet-body">

                                {% include('YtvideoBundle:Ytvideo:view.html.twig') %}

                    </div>
                    </div>
                    </div>  
                {% endblock %}
             </div>
            <div class="clearfix"></div>
       </div>
        <div class="clearfix"></div>
        {% include 'BEInterfaceBundle:_Default:footer.html.twig' %}
        <div class="clearfix"></div>

 {% endblock %}

src/Greetik/YtvideoBundle/Resources/views/Ytvideo/insert.html.twig
{% extends 'BEInterfaceBundle:_Default:modalform.html.twig' %} 

{% block modaltitle %}{% if id is defined and id!='' and id!=0 %}Editar{% else %}Añadir Nuevo{% endif %} Vídeo{% endblock %}
 
{% block modalbody %}
                        {% if form_errors(new_form) %}
                        <div class="ui-state-error">{{ form_errors(new_form) }}</div>
                       {% endif %}

                       <form class="col-md-12" action="#" id="insertvideoform">
                           
                            {% set configField = { 'label': 'Título', 'field': 'title'} %}
                            {% include 'BEInterfaceBundle:_Modules:formfieldmodal.html.twig' %}

                            {% set configField = { 'label': 'Descripción', 'field': 'comments' } %}
                            {% include 'BEInterfaceBundle:_Modules:formfieldmodal.html.twig' %}

                            {% set configField = { 'label': 'Url', 'field': 'path' } %}
                            {% include 'BEInterfaceBundle:_Modules:formfieldmodal.html.twig' %}

                            {{ form_widget(new_form['id_item'], {'attr': {'class': 'form-control'}, 'value': id_item }) }}
                            {{ form_widget(new_form['type'], {'attr': {'class': 'form-control'}, 'value': type }) }}
                            
                            {% if id is defined and id!='' and id!=0 %}
                                {{ form_widget(new_form['id'], {'attr': {'class': 'form-control'}, 'value': id }) }}
                            {% endif %}
                            
                            {{ form_widget(new_form._token) }}
                            <div class="clearfix"></div>
                       </form>

    
{% endblock %}         

{% block modalbuttons %}
    {% if id is defined and id!='' and id!=0 %}<button type="button" id="btn_deletevideo" class="btn red left">Eliminar</button>{% endif %}
    <button type="button" id="btn_savevideoyt" class="btn blue">Guardar</button>
{% endblock %}

{% block modalscripts %}
    {% set idfield = 'ytvideo_comments' %}
    {% include 'BEInterfaceBundle:_Scripts:texteditor.html.twig' %}    
    
    <script>
        $(document).ready(function() {
            $('#btn_savevideoyt').click(function(){
                if (typeof(CKEDITOR) != 'undefined') $('#ytvideo_comments').val(CKEDITOR.instances['ytvideo_comments'].getData());
                $('#buttons_modal').css('display', 'none'); $('#ajaxloader').css('display', 'block');                
                $.post('{{ path('ytvideo_insertmodifyytvideo') }}',  $("#insertvideoform").serialize() , function(r){
                    $('#buttons_modal').css('display', 'block'); $('#ajaxloader').css('display', 'none');                
                    if (r.errorCode){ alert(r.errorDescription); return; }
                    
                    {% if id is defined and id!='' and id!=0 %}
                            $('#ytvideo_{{ id }}').replaceWith(r);
                    {% else %}
                           $('#videos_{{ id_item }}').append(r);
                    {% endif %}

        
                   $('#videos_{{ id_item }}').mixitup();
                   
                    $('.modal').modal('hide');
                });               
            });
            
            $('#btn_deletevideo').click(function(){
                if (!confirm('¿Realmente desea eliminar el vídeo? OPERACIÓN IRREVERSIBLE')) return;
                $('#buttons_modal').css('display', 'none'); $('#ajaxloader').css('display', 'block');                
                $.post('{{ path('ytvideo_dropytvideo') }}',  $("#insertvideoform").serialize() , function(r){
                    $('#buttons_modal').css('display', 'block'); $('#ajaxloader').css('display', 'none');                
                    if (r.errorCode){ alert(r.errorDescription); return; }
                    
                    $('#ytvideo_{{ id }}').remove();
                    
                     alert('El vídeo ha sido eliminado correctamente');
                    
                    $('.modal').modal('hide');
                });               
            });
            
        });
     </script>
 {% endblock %}

src/Greetik/YtvideoBundle/Resources/views/Ytvideo/view.html.twig
{# 
Pacolmg
Greetik Soluciones SL
Template to view a list of youtube videos
#}
{% if configFiles['modifyAllow'] is defined and configFiles['modifyAllow']==true %}
    <div class="btn-group">
        <a data-toggle="modal" data-target="#modal_ajax" href="{{ path('ytvideo_insertformytvideo', {'id_item': configFiles['id'], 'type': configFiles['type'] }) }}" class="btn btn red">Nuevo <i class="fa fa-youtube"></i></a>
    </div>
    {% endif %}

    <!-- BEGIN FILTER -->           
      <div class="margin-top-10">
        <ul class="mix-filter">
          <li class="filter" data-filter="all" style="display:none">Todos</li>
       </ul> 
      {% if ytvideos is defined %}
       <div class="row mix-grid thumbnails" id="videos_{{ configFiles.id }}" >
          {% for ytvideo in ytvideos %}
                {% include('YtvideoBundle:Ytvideo:ytvideo.html.twig') %}
          {% endfor %}
       </div>
       {% endif %}
    </div>
    <!-- END FILTER -->             
    
    {% set idportfolio = "videos_"~configFiles.id %}
    {% include('BEInterfaceBundle:_Scripts:portfolioimages.html.twig') %}
    
    <script>
        $(document).ready(function(){
            $( "#videos_{{ configFiles.id }}" ).sortable({
                //items: ".template-download:not(.clearfix)",
                cursor: "move",
                stop: function( event, ui ) {
                    var _itemposition = ui.item.index()
                    
                    //save the new position
                   $.post("{{ path('ytvideo_moveytvideo') }}", { id: ui.item.attr('data-id'), newposition: _itemposition  },function(r){
                        if (r.errorCode>0){alert("Error Moviendo Imagen: "+r.errorDescription);return;}
                    });                    
                }
            });
            $( "#gallery_files_{{ configFiles.id }} .clearfix" ).disableSelection();            
        });
        
            
    </script>

src/Greetik/YtvideoBundle/Resources/views/Ytvideo/ytvideo.html.twig
<div class="col-md-3 col-sm-4 mix category_1 mix_all" id="ytvideo_{{ ytvideo.id }}" data-id="{{ ytvideo.id }}" style="display: inline-block;  opacity: 1;">             
    <div class="mix-inner">
        <img class="img-responsive" src="{{ ytvideo.thumbnail }}" alt="">
        <div class="mix-details">
           <h4>{{ ytvideo.title }}</h4>
           {% if configFiles['modifyAllow'] is defined and configFiles['modifyAllow']==true %}<a data-toggle="modal" data-target="#modal_ajax" class="mix-link" href="{{ path('ytvideo_insertformytvideo', {'id_item': configFiles.id, 'id': ytvideo.id, 'type': configFiles.type }) }}"><i class="fa fa-link"></i></a>{% endif %}
           <a class="mix-preview fancybox-button fancybox.iframe" href="{{ ytvideo.embedurl }}" title="ver Vídeo" data-rel=""><i class="fa fa-search"></i></a>
        </div>
     </div>
</div>        